"""Add new models or schema changes

Revision ID: 5d4922d76559
Revises: 3781e22d8b01
Create Date: 2025-03-03 17:14:17.733911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d4922d76559'
down_revision: Union[str, None] = '3781e22d8b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('resource_link', sa.String(), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('sync_interval', sa.Integer(), nullable=True),
    sa.Column('page_token', sa.String(), nullable=True),
    sa.Column('start_sync_token', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('resource_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('memory_id', table_name='memory')
    op.drop_table('memory')
    op.drop_table('channel_member')
    op.drop_index('function_id', table_name='function')
    op.drop_table('function')
    op.drop_index('document_collection_name', table_name='document')
    op.drop_index('document_name', table_name='document')
    op.drop_table('document')
    op.drop_table('feedback')
    op.drop_table('message')
    op.drop_table('config')
    op.drop_index('prompt_command', table_name='prompt')
    op.drop_table('prompt')
    op.drop_index('chatidtag_id', table_name='chatidtag')
    op.drop_table('chatidtag')
    op.drop_index('tool_id', table_name='tool')
    op.drop_table('tool')
    op.drop_table('channel')
    op.drop_table('message_reaction')
    op.drop_index('model_id', table_name='model')
    op.drop_table('model')
    op.drop_table('knowledge')
    op.drop_table('folder')
    op.drop_table('migratehistory')
    op.alter_column('auth', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('auth', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('auth', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('auth_id', table_name='auth')
    op.alter_column('chat', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('chat', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('chat', 'updated_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('chat', 'share_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('chat', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chat', 'meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_index('chat_id', table_name='chat')
    op.drop_index('chat_share_id', table_name='chat')
    op.create_unique_constraint(None, 'chat', ['share_id'])
    op.add_column('file', sa.Column('file_id', sa.String(), nullable=True))
    op.add_column('file', sa.Column('modified_time', sa.String(), nullable=True))
    op.add_column('file', sa.Column('external_source_id', sa.Integer(), nullable=True))
    op.alter_column('file', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('file', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('file', 'filename',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('file', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('file_id', table_name='file')
    op.create_foreign_key(None, 'file', 'external_resources', ['external_source_id'], ['id'])
    op.create_unique_constraint(None, 'group', ['id'])
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'profile_image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'last_active_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('user', 'updated_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('user_api_key', table_name='user')
    op.drop_index('user_id', table_name='user')
    op.drop_index('user_oauth_sub', table_name='user')
    op.create_unique_constraint(None, 'user', ['api_key'])
    op.create_unique_constraint(None, 'user', ['oauth_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('user_oauth_sub', 'user', ['oauth_sub'], unique=True)
    op.create_index('user_id', 'user', ['id'], unique=True)
    op.create_index('user_api_key', 'user', ['api_key'], unique=True)
    op.alter_column('user', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('user', 'last_active_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('user', 'profile_image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'group', type_='unique')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_index('file_id', 'file', ['id'], unique=True)
    op.alter_column('file', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('file', 'filename',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('file', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('file', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('file', 'external_source_id')
    op.drop_column('file', 'modified_time')
    op.drop_column('file', 'file_id')
    op.drop_constraint(None, 'chat', type_='unique')
    op.create_index('chat_share_id', 'chat', ['share_id'], unique=True)
    op.create_index('chat_id', 'chat', ['id'], unique=True)
    op.alter_column('chat', 'meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('chat', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chat', 'share_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('chat', 'updated_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('chat', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('chat', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index('auth_id', 'auth', ['id'], unique=True)
    op.alter_column('auth', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('auth', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('auth', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('migratehistory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('migrated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='migratehistory_pkey')
    )
    op.create_table('folder',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_expanded', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'user_id', name='folder_pkey')
    )
    op.create_table('knowledge',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('access_control', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='knowledge_pkey')
    )
    op.create_table('model',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('base_model_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('params', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('access_control', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False)
    )
    op.create_index('model_id', 'model', ['id'], unique=True)
    op.create_table('message_reaction',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_reaction_pkey')
    )
    op.create_table('channel',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('access_control', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='channel_pkey')
    )
    op.create_table('tool',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('specs', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('valves', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('access_control', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.create_index('tool_id', 'tool', ['id'], unique=True)
    op.create_table('chatidtag',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False)
    )
    op.create_index('chatidtag_id', 'chatidtag', ['id'], unique=True)
    op.create_table('prompt',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('command', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('access_control', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='prompt_pkey')
    )
    op.create_index('prompt_command', 'prompt', ['command'], unique=True)
    op.create_table('config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='config_pkey')
    )
    op.create_table('message',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_pkey')
    )
    op.create_table('feedback',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey')
    )
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collection_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='document_pkey')
    )
    op.create_index('document_name', 'document', ['name'], unique=True)
    op.create_index('document_collection_name', 'document', ['collection_name'], unique=True)
    op.create_table('function',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('valves', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_global', sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.create_index('function_id', 'function', ['id'], unique=True)
    op.create_table('channel_member',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='channel_member_pkey')
    )
    op.create_table('memory',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False)
    )
    op.create_index('memory_id', 'memory', ['id'], unique=True)
    op.drop_table('external_resources')
    # ### end Alembic commands ###
