"""Create channel table

Revision ID: c138084341f1
Revises: 71618886c456
Create Date: 2025-03-03 14:31:14.169758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c138084341f1'
down_revision: Union[str, None] = '71618886c456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('chatidtag_id', table_name='chatidtag')
    op.drop_table('chatidtag')
    op.drop_index('prompt_command', table_name='prompt')
    op.drop_table('prompt')
    op.drop_table('migratehistory')
    op.drop_index('function_id', table_name='function')
    op.drop_table('function')
    op.drop_index('memory_id', table_name='memory')
    op.drop_table('memory')
    op.drop_index('document_collection_name', table_name='document')
    op.drop_index('document_name', table_name='document')
    op.drop_table('document')
    op.drop_index('tool_id', table_name='tool')
    op.drop_table('tool')
    op.drop_table('config')
    op.drop_index('model_id', table_name='model')
    op.drop_table('model')
    op.drop_index('auth_id', table_name='auth')
    op.drop_index('chat_id', table_name='chat')
    op.drop_index('file_id', table_name='file')
    op.drop_index('tag_id', table_name='tag')
    op.drop_index('user_id', table_name='user')
    op.drop_column('user', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timestamp', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_index('user_id', 'user', ['id'], unique=True)
    op.create_index('tag_id', 'tag', ['id'], unique=True)
    op.create_index('file_id', 'file', ['id'], unique=True)
    op.create_index('chat_id', 'chat', ['id'], unique=True)
    op.create_index('auth_id', 'auth', ['id'], unique=True)
    op.create_table('model',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('base_model_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('params', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False)
    )
    op.create_index('model_id', 'model', ['id'], unique=True)
    op.create_table('config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='config_pkey')
    )
    op.create_table('tool',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('specs', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('valves', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('tool_id', 'tool', ['id'], unique=True)
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collection_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='document_pkey')
    )
    op.create_index('document_name', 'document', ['name'], unique=True)
    op.create_index('document_collection_name', 'document', ['collection_name'], unique=True)
    op.create_table('memory',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False)
    )
    op.create_index('memory_id', 'memory', ['id'], unique=True)
    op.create_table('function',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('valves', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_global', sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.create_index('function_id', 'function', ['id'], unique=True)
    op.create_table('migratehistory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('migrated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='migratehistory_pkey')
    )
    op.create_table('prompt',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('command', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='prompt_pkey')
    )
    op.create_index('prompt_command', 'prompt', ['command'], unique=True)
    op.create_table('chatidtag',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False)
    )
    op.create_index('chatidtag_id', 'chatidtag', ['id'], unique=True)
    # ### end Alembic commands ###
